# Generated by Django 3.2.5 on 2021-08-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_note_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
