# Generated by Django 3.2.4 on 2021-08-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
