# Generated by Django 3.2.4 on 2021-08-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_last_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='last_edited',
        ),
    ]
